export const SWAGGER_API_TAG = 'study';
export const SWAGGER_API_NAME = 'GOLINE API';
export const SWAGGER_API_DESCRIPTION =
  'API IMPLEMENTADA PARA PRATICAR OS MELHORES PATTERNS E RECURSOS ATUAIS NO DESENVOLVIMENTO DE SW';
export const SWAGGER_API_CURRENT_VERSION = '1.0';
